# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
   
jobs:
# Job#1
  Build:

    runs-on: self-hosted
    env:
     JAVA_HOME: C:\Program Files\Java\jdk-11.0.10

    steps:
    
    - name: Checkout the code
      uses: actions/checkout@v2
      with:
       ref: main
      
    
    - name: Build with Maven
      run: |
           cd HelloWorld;
           mvn clean install
           
    #- name: Upload to Artifactory
    #  run:  Remove-item alias:curl;
     #       curl -X PUT -u ${{ secrets.USER }}:${{ secrets.PASSWORD }} -T C:\Artifactory\Actions\ArtifactoryRepo\Artifactory\Artifactory\target\SubmissionDataForm-0.0.1-SNAPSHOT.jar "http://localhost:8082/artifactory/CG-libs-release-local/SubmissionDataForm-0.0.1-SNAPSHOT.jar"

  
   
