# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
   inputs:
    Type:
     description: 'Enter the type of Artifact'
     required: true
     default: ''
   
jobs:
# Job#1
  Build:

    runs-on: ubuntu-latest
    #env:
     #JAVA_HOME: C:\Program Files\Java\jdk-11.0.10

    steps:
    
    - name: Checkout the code
      uses: actions/checkout@v2
      with:
       ref: main
      
    - name: Get current date
      id: date
      #run: echo "::set-output name=date::$(date +'dd/MM/yyyy')"
      run:  echo "::set-output name=date::$( Get-Date -Format "MM-dd-yyyy")"
      
    - name: Build with Maven
      run: |
           cd HelloWorld;
           echo "Type is: ${{ github.event.inputs.Type }}"
           mvn clean install '-Ddate= ${{ steps.date.outputs.date }}' '-Dtype=${{ github.event.inputs.Type }}'
    - name: Veracode scan
      uses: veracode/veracode-uploadandscan-action@master
      with:
        filepath: 'HelloWorld/target/'
        vid: 'eb2e5e1210cf22ea1f46302694d7e34c'
        vkey: '189c653a023307de5b4aab640a8c77fef4707d3a90814239c03ca7c1cbaa8e8ca49c565a86078d746c9b49de21c24a65229ae1a1a0514a090cc73ea07ca810aa'
        createsandbox: 'true'
        sandboxname: 'SANDBOXNAME'
        scantimeout: 15
        exclude: '*.js'
        include: '*.war'
        criticality: 'Medium'
